### ISSUE TITLE
BoxKeyError when using setdefault

### ISSUE THREAD

**Issue by thnee** [dynaconf/dynaconf#1113]
The following code raises `BoxKeyError`.
```python
my_flask_dynaconf.init_app(app)
asdf = app.config.setdefault("ASDF", {})
asdf.setdefault("qwer", "zxcv")
qwer = app.config["ASDF"]["qwer"]
```

The reason for bringing this up is because the Flask extension Flask-Alembic uses this code pattern.

Please see [the Flask-Alembic source code](https://github.com/pallets-eco/flask-alembic/blob/3.1.0/src/flask_alembic/extension.py).
On line 150 and 151 `script_location` is defined.
On line 215 `script_location` is accessed, and this is where Dynaconf raises `BoxKeyError`.

It would be good if these libraries could be used at the same time.
Is there anything that could be changed in Dynaconf to accommodate for this pattern? Or is this pattern incompatible with Dynaconf?

It is possible to workaround the issue, by moving the call to Flask-Alembic's `init_app` so that it occurs before the call to Dynaconf's Flask `init_app`.
But that probably does not count as a proper solution. Ideally, Dynaconf's Flask `init_app` should be the first one to be called, so that config is loaded before everything else.

**Comment by rochacbruno** [comment]
I was able to reproduce and figure out where the problem is caused, however it is a tricky issue to solve.

## Explanation

Dynaconf sets `app.config` as a `Dynaconf` instance, this object has multi interface lookup, which means you can access nested structures with subscription `app.config["THING]["OTHER"]` and also works if you use attributes `app.config.THING.OTHER` and also this access is case-insensitive so you can do `app.config.thing.Other` and `app.config.Thing["other"]`

To provide that feature Dynaconf wraps every `dict` with a `DynaBox` instance, which is the object providing those access methods.

When you do `x = app.config.setdefault("thing", mydict)` what you get back is not the very same `mydict` object in memory, but a new instance of `DynaBox` initialized from `mydict` key, values.

Now when you do `x.setdefault...` you are mutating that instance of DynaBox that will not reflect on the "thing" value inside the settings.

I was able to fix the issue by adding a `compatibility_mode=True` https://github.com/dynaconf/dynaconf/pull/1115 

## Compatibility mode

Dynaconf transform nested data structures to a new DynaBox instance, this is an
object that allows dot notation access such as `app.config.key.value.other`.
However this feature is imcompatible with some Flask extensions, for example:
`Flask-Alembic`.

So in case you see a `BoxKeyError` when running your app with you can run it on
compatibility mode.

```python
FlaskDynaconf(app, compatibility_mode=True)
```

The downside is that now you cannot access nested elements using dot notation
but the usual access interface via dict subscription will work normally:
`app.config["KEY"]["value"]["other"]`

!!! info
    On Dynaconf 4.0 compatibility_mode will default to True when running
    on Flask.

**Comment by rochacbruno** [comment]
@pedro-psb on our last meeting you mentioned about disabling dot access and I now agree with you, on the breaking 4.0 release we must disable DynaBox!

**Comment by thnee** [comment]
Thank you for the super fast response!

Just wanted to ask, why does this particular thing require a different mode of operation?
`DynaBox` currently implements various getters like `__getattr__` and `__getitem__`, `get`, `__dir__`.
Is there some particular reason why it couldn't also implement setters like `__setitem__`, `update`, and `setdefault`? And perhaps even `__delitem__`?

I'm not very familiar with the DynaConf code base, so I could be totally missing something.
And I don't use the dot notation anyway, so this compatibility mode should probably work fine for me personally.
Just wanted to understand the design.
