### ISSUE TITLE
Improve documentation about the default_env [was] `default_env` is documented but seems non-existant

### ISSUE THREAD

**Issue by Horgix** [dynaconf/dynaconf#461]
**Describe the bug**

As expected from the documentation, defining the `default_env` property on a `Dynaconf` object should change the default environment used to load configuration. However, it currently doesn't work at all, and searching for `default_env` among the code yields no result whatsoever except from the documentation (maybe it's handled by a dependency, but the thing is that it doesn't work).

**To Reproduce**

1. Having the following folder structure

<details>
<summary>Project structure</summary>

```bash
# config.py
# settings.toml
```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**settings.toml**
```toml
[default]
foo = "default"

[development]
foo = "dev"

[production]
foo = "prod"
```
</details>

3. Having the following app code:

<details>
<summary>Code</summary>

**config.py**
```python
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    environments=True,
    default_env="production",
    settings_file="settings.toml",
)

print(settings.current_env) # will print DEVELOPMENT
print(settings.foo) # will print dev
```
</details>

4. Executing under the following environment

<details>
<summary>Execution</summary>

```bash
# Virtualenv with Python 3.8.6 and only dynaconf installed through pip

$ python config.py
DEVELOPMENT
dev
```
</details>

**Expected behavior**
Expecting the `default_env` to work, so essentially the following output:

```bash
$ python config.py
PRODUCTION # or production, doesn't matter
prod
```

**Environment (please complete the following information):**
 - OS: Arch Linux
 - Dynaconf Version 3.1.2

**Additional context**
Nothing more, except saying that Dynaconf has so far been an awesome lib and I really wish this worked <3

**Comment by Horgix** [comment]
Would also like to note that if this gets confirmed I would be happy to work on fixing it (and hey, it's Hacktoberfest!)

**Comment by rochacbruno** [comment]
default env is defined here:https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/default_settings.py#L109

when it is passed to Dynaconf class it gets loaded here: https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/base.py#L122-L136

Then finally the value is used here https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/loaders/base.py#L130

here https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/loaders/base.py#L116

and here: https://github.com/rochacbruno/dynaconf/blob/56130a8b09779f13ae1d843e3e326739f63c5bec/dynaconf/utils/__init__.py#L253

**Comment by Horgix** [comment]
Thanks for the code links! That being said, did you take a look at the code & execution samples in the report? Did I miss anything or does it indeed not work as expected?

**Comment by humrochagf** [comment]
I don't think there's a bug here, maybe it needs some clarification on the docs but what happens is that `default_env` is the environment where the default values are defined, and the `env` is the one that holds the current environment being executed.

You defined `production` as the one that sets all default values of your project, then toggled the `development` environment (development is the default since you didn't fill the env parameter) to set the environment-specific values.

We can't see it happening because the `foo` on development is overriding the `foo` from production but if you add another variable to production (let's say `bar`) and don't add it to development you will see that bar was loaded with your `default_env` value.

But to achieve the correct intended behaviour you were seeking with your code you must pass the `env` parameter instead of `default_env` on your `config.py` file

**Comment by rochacbruno** [comment]
@humrochagf you are right, this is not a bug, but maybe we need to explain it better on the docs that

default_env = from where default values comes from
current_env = the env your application reads from at any time (which overrides the values from default)

default is something like `original`, `base` but the name `default` is common usage in this case
