### ISSUE TITLE
Import/include settings from another file?

### ISSUE THREAD

**Issue by wgordon17** [dynaconf/dynaconf#859]
Where possible, I prefer to keep my settings explicitly defined. To that end, I'd like to define a "default" settings file (`django-default.yaml`) that would contain all of the "default" Django settings, and then define my override settings file (`settings.yaml`) where I either inherit/import/include the settings from `django-default.yaml`, and then maintain my _project-specific_ settings.

While I know this is possible in a single `settings.yaml` file with the `default` environment, it fills up the settings file pretty quickly and makes it harder to parse for just the "important" stuff.

This _seems like_ a use case for [Preloading files](https://www.dynaconf.com/advanced/#preloading-files), but it would help to understand if there's a better pattern or suggestion for this.

**Comment by rochacbruno** [comment]
I think this is about documenting a workflow where the project have a default settings definition and how to override/extend from specific files, this is the most common use case and can be achieved by following merging strategies.

Example:

On the main application a `default-settings.yaml` is placed

```yaml
default:
    options:
        power_mode: true
        flux_capacitor_enabled: true
        flux_capacitor_options:
            potency: 1000
```

Then on the application (can be a django, flask or any application

```python
settings = Dynaconf(
    settings_files=["default-settings.yaml", "*.yaml"]
)
```

Now if you run the application you are going to have settings loaded from the default settings so

```python
assert settings.options.power_mode is True
```

Now you can place a second yaml file on a place discoverable by dynaconf (or you set absolute paths or a root_path)

**The Wrong Way**
`my-specific-settings.yaml`
```yaml
default:
    options:
        flux_capacitor_enabled: false
```

The above will override the entire `settings.options` with this new one so the keys `power_mode` and `flux_capacitor_options` will be gone.

To fix that problem there are 3 options:

1. Enable global merge by setting `merge_enabled=True` on your Dynaconf instance.  (on django plugin pass MERGE_ENABLED_FOR_DYNACONF=True`)

2. Use local merge only on specific keys 

`my-specific-settings.yaml`
```yaml
default:
    options:
        dynaconf_merge: true
        flux_capacitor_enabled: false
```

3. Use dunder settings

Settings with `__` separator always merges with existing data structures

```yaml
default:
    options__flux_capacitor_enabled: true
```

So that is the first part of the question: **How to compose settings from multiple files**

Now lets see how to reuse values from other settings using variable interpolation.

```yaml
default:
    options__flux_capacitor_options__max_potency: "@int @jinja {{this.options.flux_capacitor_options.potency * 25}}"
```

The lazy evaluated variables are defined with either `@format` (calls str.format) or `@jinja` (calls Jinja parser), inside those templates you have access to `this` (the settings object) and `env` (all environment variables).

This can be combined with other converters like `@int, @str, @float` etc

You can also add custom converters https://www.dynaconf.com/envvars/#adding-a-custom-casting-token

---

I am not sure this fits your use case, if not, can you please provide more context with examples of code and what the expected behavior?
