### ISSUE TITLE
[bug] dynaconf.loaders.write does not support merge argument

### ISSUE THREAD

**Issue by Holzhauer** [dynaconf/dynaconf#874]
**Describe the bug**
Despite its [documentation](https://www.dynaconf.com/advanced/#exporting) [loaders.write()](url) does not support the `merge` argument, which is available at `loader.write()`, where `loaders.write()` delegates to (it sets the argument to `False`),

**To Reproduce**
Having `settings.toml` in the root path.

Having the following app code:
 
```python
from dynaconf import Dynaconf
from dynaconf import loaders
from dynaconf import settings
from dynaconf.utils.boxing import DynaBox

settings = Dynaconf(settings_files=["settings.toml",])

data = settings.as_dict(env='development')
loaders.write('export.yaml', DynaBox(data).to_dict(), merge=False, env='development')
```

**Expected behavior**
Above code runs without error.

**Environment (please complete the following information):**
 - OS: Windows/10 Enterprise
 - Dynaconf Version: 3.1.11

**Comment by rochacbruno** [comment]
similiar to #839 we need to fix it

**Comment by pedro-psb** [comment]
This is working. Maybe we should add some tests?
If so, it should cover all core loaders, because each one of them should accept and handle `merge` correctly.

Refactor suggestion: It may be better to have the context (`loaders.write`) handle the merge option, so individual `loader.write` would just receive data and assume it was handled correctly. This would make it easier to test and harder to introduce bugs.

**Comment by rochacbruno** [comment]
@pedro-psb the fix was introduced in https://github.com/dynaconf/dynaconf/pull/875/files but not released yet

You are suggesting to pass `**kwargs` to that function?

**Comment by pedro-psb** [comment]
Not really. Indeed, I forget about a detail when I did the previous comments. Because merging requires the file to be opened first, this would require the outer context to have the specific file format readers/parsers. So maybe all the logic (read/parse + write to file) could be uplifted. At the end, it would be like a functional template method pattern for the module. I'll provide a sample of how this could work below.

Another way I thought (and prefer) was to turn loaders into classes (and then use regular template pattern). I think it would provide better interface for custom loaders too. By providing basically the `parser` and the `writter`, the custom loader would leverage dynaconf merging options for free. This would be a more long run proposal, maybe 4.0.0

The first proposal (simpler) would be like this:

 **Current (simplified)**
```python
# loaders/__init__.py
def write(filename, data, env, merge=False):
	loader = globals().get(loader_name)
	loader.write(filename, data, env, merge)

# loaders/toml_loader.py (same to all loaders)
def writer(filename, data, merge) -> Writer:
	with open(filename) as file:
		if merge:
			# specific reading data for merge
		# specific data writting
```

**First Proposal (simplified)**

```python
# loaders/__init__.py
def write(filename, data, env, merge=False):
	loader = globals().get(loader_name)
	file_parser = loader.parser()
	file_writer = loader.writer()

	# now this common logic is shared (BaseLoader does something similar)
	with open(filename) as file:
		if merge:
			object_merge(file_parser(file), data)
		file_writer(file, data)

# loaders/toml_loader.py (applys to all)
Parser = Callable[[File], dict]
def parser() -> Parser:
	"""Return function that reads/parse the file into data (for merging)"""
	return tomllib.load
	# maybe return tuple so it's consumer may try to use fallback parser
	# return (tomlib.load, toml.load)

Writer = Callable[[File, dict], None]
def writer() -> Writer:
	"""Return function that writes format data to file"""
	return lambda file, data: tomllib.dump(enconde_nulls(data), file)
```
